googleapis/ruby-spanner-activerecord

- .github/sync-repo-settings.yaml
These non-existent checks are currently preventing us from merging PRs. Instead, we plan to setup GitHub Actions (#47).
> test: remove non-existant checks

- README.md
Previously URLs on README.md was not correct.
It contains `USERNAME` and wrong repository name.
Now, they are fixed to point at this repository.
https://github.com/googleapis/ruby-spanner-activerecord
> Fix draft version of URLs on README.md

- .rubocop.yml
- CONTRIBUTING.md
This PR enables developer to run RuboCop when they install dependent gems by `bundle install --path=vendor/bundle`
* Like `.gitignore`, ignore files under the `vendor` which is populated with Ruby files.
* Fix commands on `CONTRIBUTING.md`
* Add information on `googleapis/ruby-style`
* Change `rake rubocop` to `rubocop` according to https://github.com/googleapis/ruby-style#usage
* If we prefer `rake rubocop` style, I will edit `Rakefile` to include RuboCop tasks.
> Improve settings and documents to run RuboCop locally

- .github/workflows/ci.yaml
- .github/workflows/test.yaml
This covers basic test by running `bundle exec rake test`.
c.f. #47
* As a first step, acceptance test is out of the scope of this Pull Request.
* To avoid conflict with #49, I did not include badge on README.md.
These can be implemented afterwards.
You can see how this works at 
https://github.com/aeroastro/ruby-spanner-activerecord/pull/1
> Add basic test on GitHub Actions

- bin/console
Previously, `bin/console` does not work because of wrong gem path. ( `activerecord/spanner` )
```
$ ./bin/console
Traceback (most recent call last):
1: from ./bin/console:4:in `<main>'
./bin/console:4:in `require': cannot load such file -- activerecord/spanner (LoadError)
```
This patch fixes the above issue and improves gem development as follows.
* Fix gem path from `activerecord/spanner` to `activerecord-spanner-adapter`
* Use `pry` and `pry-byebug` instead of `irb`. (This helps development especially when we use old Ruby versions)
* Require `active_record`. (This is indispensable for gem development)
> Enable and improve `bin/console` for easier gem development

- Gemfile
- Rakefile
- acceptance/cases/migration/column_attributes_test.rb
- acceptance/cases/migration/columns_test.rb
- acceptance/cases/migration/command_recorder_test.rb
- acceptance/cases/migration/rename_column_test.rb
- activerecord-spanner-adapter.gemspec
- lib/active_record/connection_adapters/spanner/schema_definitions.rb
- lib/activerecord_spanner_adapter/connection.rb
- lib/spanner_client_ext.rb
- test/activerecord_spanner_adapter/connection_test.rb
- test/test_helper.rb
Fixes issue:  https://github.com/googleapis/ruby-spanner-activerecord/issues/52
- Upgraded `google-cloud-spanner` gem version upgraded from 1.6 to 2.2
- Fix unit and acceptance tests
Note: Upgrade will help us to add emulator support.
> feat: google-cloud-spanner version upgraded to 2.2

- activerecord-spanner-adapter.gemspec
- lib/activerecord_spanner_adapter/connection.rb
@jiren 
This is not fully-functional support for Spanner Emulator, but the first step.
I have updated the `google-cloud-spanner` to 2.4 to include https://github.com/googleapis/google-cloud-ruby/pull/8416,
and pass the `emulator_host` to `Google::Cloud::Spanner.new`.
This makes the following code working.
```ruby
ActiveRecord::Base.establish_connection(
adapter: :spanner,
project: 'test-project',
instance: 'test-instance',
database: 'test-database',
emulator_host: 'localhost:9010'
)
ActiveRecord::Base.tap(&:connection).connected?
```
The reasons why I omit the test codes are:
* This part is not something to be fully tested.
* Actually, I did not find existing test on checking the arguments passed to `Google::Cloud::Spanner`
* In the future, I would like to run acceptance test with Spanner …
> Add basic emulator support with updated `google-cloud-spanner`

- acceptance/cases/transactions/read_write_transactions_test.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/activerecord_spanner_adapter/transaction.rb
- lib/spanner_client_ext.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
Adds support for PDML transactions. These can be used for updates of large amounts of data, such as for example when copying the data from column to another.
> feat: support PDML transactions

- acceptance/cases/migration/command_recorder_test.rb
- lib/active_record/connection_adapters/spanner/schema_statements.rb
There was a change in the method definition for `add_foreign_key` between versions [6.0.2](https://github.com/rails/rails/blob/f675cb30ce813a99b52b139a93e048330922fd9a/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L991) and [6.0.3](https://github.com/rails/rails/blob/b738f1930f3c82f51741ef7241c1fee691d7deb2/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L991) in ActiveRecord.
Should fix the build error in https://github.com/googleapis/ruby-spanner-activerecord/runs/3101059202?check_suite_focus=true
> fix: add_foreign_key def was changed in 6.0.3

- .github/workflows/release-please-label.yml
- .github/workflows/release-please.yml
- .gitignore
- .kokoro/populate-secrets.sh
- .kokoro/release.cfg
- .kokoro/release.sh
- .kokoro/trampoline_v2.sh
- .toys/release.rb
- .trampolinerc
- CHANGELOG.md
This is the package of release jobs and scripts for Ruby repositories. It includes:
* A release-please GitHub Action that runs nightly and can also be kicked off on demand. It covers all gems in this repo (currently just activerecord-spanner-adapter).
* A kokoro job that performs an actual gem release, which will be triggered automatically by the autorelease bot when a release-please PR is merged. The kokoro job is also configured to build docs and push them to googleapis.dev. (The ability to push to cloud-rad is also implemented, and just needs a config change to activate.)
This uses:
* Trampoline V2 for running kokoro jobs in a docker container. The release job uses the same docker image (defined in the https://github.com/googleapis/testing-infra-docker repo) used by other Ruby repos.
* …
> chore: Install release jobs and scripts

- acceptance/cases/type/all_types_test.rb
- acceptance/cases/type/json_test.rb
- acceptance/schema/schema.rb
- acceptance/test_helper.rb
- activerecord-spanner-adapter.gemspec
- lib/active_record/connection_adapters/spanner_adapter.rb
- lib/active_record/type/spanner/spanner_active_record_converter.rb
- test/activerecord_spanner_adapter/connection_mock_server_test.rb
- test/activerecord_spanner_adapter/table/column_test.rb
- test/activerecord_spanner_mock_server/model_helper.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
- test/migrations_with_mock_server/db/migrate/03_create_all_native_migration_types.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
- test/mock_server/spanner_mock_server_test.rb
- test/mock_server/statement_result.rb
Adds support for the JSON data type to the ActiveRecord provider.
Note: Acceptance tests for JSON are skipped on the emulator, as the emulator does not yet support this data type. This also means that we cannot yet add a standalone sample for how to use this data type.
> feat: support JSON data type

- .github/workflows/acceptance-tests-on-production.yaml
Only run acceptance tests on production when the PR actually has access to the GitHub secrets. This basically restricts the step to only PRs and pushes that are made directly to this repo, instead of in forks.
See #122 for an example of the same change from a fork. That PR skips the acceptance tests on production step as it does not have access to the secrets.
> build: skip acceptance tests on prod when secrets are not available

- acceptance/cases/transactions/read_only_transactions_test.rb
- examples/snippets/read-only-transactions/application.rb
- examples/snippets/read-only-transactions/db/schema.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/activerecord_spanner_adapter/transaction.rb
- test/activerecord_spanner_mock_server/read_only_transaction_test.rb
Adds support for setting a timestamp bound when executing a read-only transaction. This allows users to use a read-only transaction to read stale data instead of the most recent data, which can be more efficient when direct consistency is not required.
> feat: support stale reads in read-only transactions

- acceptance/cases/transactions/read_only_transactions_test.rb
- examples/snippets/stale-reads/README.md
- examples/snippets/stale-reads/Rakefile
- examples/snippets/stale-reads/application.rb
- examples/snippets/stale-reads/config/database.yml
- examples/snippets/stale-reads/db/migrate/01_create_tables.rb
- examples/snippets/stale-reads/db/schema.rb
- examples/snippets/stale-reads/db/seeds.rb
- examples/snippets/stale-reads/models/album.rb
- examples/snippets/stale-reads/models/singer.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/activerecord_spanner_adapter/connection.rb
- lib/arel/visitors/spanner.rb
- lib/spanner_client_ext.rb
- test/activerecord_spanner_mock_server/read_only_transaction_test.rb
- test/mock_server/spanner_mock_server.rb
Adds support for executing stale reads outside transactions. This feature uses the `optimizer_hints` feature that was introduced in ActiveRecord 6. The specific optimizer hints are not translated into actual hints for Spanner, but are translated into a specific single use transaction option for the query.
> feat: support single stale reads

- lib/active_record/tasks/spanner_database_tasks.rb
`activerecord-spanner-adapter` raises `ActiveRecord::Tasks::DatabaseAlreadyExists` when `db:create` was failed, but `ActiveRecord::DatabaseAlreadyExists` is correct.
see: https://api.rubyonrails.org/classes/ActiveRecord/DatabaseAlreadyExists.html
> Fix wrong exception was raised when db:create

- acceptance/cases/models/query_test.rb
- examples/snippets/hints/README.md
- examples/snippets/hints/Rakefile
- examples/snippets/hints/application.rb
- examples/snippets/hints/config/database.yml
- examples/snippets/hints/db/migrate/01_create_tables.rb
- examples/snippets/hints/db/schema.rb
- examples/snippets/hints/db/seeds.rb
- examples/snippets/hints/models/album.rb
- examples/snippets/hints/models/singer.rb
- lib/arel/visitors/spanner.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
Adds support for statement-, table- and join hints. Also includes a sample for how these can be used.
Fixes #131
> feat: add support for query hints

- examples/snippets/partitioned-dml/README.md
- examples/snippets/partitioned-dml/Rakefile
- examples/snippets/partitioned-dml/application.rb
- examples/snippets/partitioned-dml/config/database.yml
- examples/snippets/partitioned-dml/db/migrate/01_create_tables.rb
- examples/snippets/partitioned-dml/db/schema.rb
- examples/snippets/partitioned-dml/db/seeds.rb
- examples/snippets/partitioned-dml/models/album.rb
- examples/snippets/partitioned-dml/models/singer.rb
Adds a sample for using Partitioned DML with the ActiveRecord Spanner adapter.
> docs: add sample for Partitioned DML

- README.md
Documents the limitations regarding using interleaved tables with the Spanner ActiveRecord provider.
> docs: Document interleaved table limitation

- README.md
- lib/activerecord_spanner_adapter/connection.rb
- lib/activerecord_spanner_adapter/transaction.rb
- lib/spanner_client_ext.rb
- test/activerecord_spanner_mock_server/inline_begin_transaction_test.rb
- test/activerecord_spanner_mock_server/optimistic_locking_test.rb
- test/activerecord_spanner_mock_server/session_not_found_test.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
- test/mock_server/spanner_mock_server.rb
- test/mock_server/statement_result.rb
Replaces the `BeginTransaction` RPC invocation at the beginning of a read/write transaction with an inlined `BeginTransaction` option on the first statement in the transaction. This reduces the number of roundtrips by one for read/write transactions that execute at least one SQL statement (DML or query).
Transactions that only execute one or more mutations still need to execute a `BeginTransaction` RPC before the `Commit`.
The [inline_begin_transaction_test.rb](https://github.com/googleapis/ruby-spanner-activerecord/blob/35df01ca87d72cdbbf3d1a3e63736c88462c48cc/test/activerecord_spanner_mock_server/inline_begin_transaction_test.rb) file is a good starting point for reviewing this PR, as it gives an overview of how the provider behaves for different scenarios.
```
Benchmarks for …
```
> perf: inline BeginTransaction with first statement in the transaction

- examples/snippets/interleaved-tables/README.md
- examples/snippets/interleaved-tables/db/migrate/01_create_tables.rb
- examples/snippets/interleaved-tables/db/schema.rb
- test/migrations_with_mock_server/db/migrate/04_create_singer_and_album_and_track_tables.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
Interleaved child tables should have a unique index on the child id column to prevent full
table scans when a single child record is fetched by ActiveRecord. ActiveRecord will only
use the child id column when fetching a record, and this query will not use the primary key
of the table, as that primary key starts with the parent id column(s).
> docs: add unique index to interleaved table sample

- README.md
This is used for triggering a release manually.
> chore: create a GA release as v1.0.0

- .github/sync-repo-settings.yaml
- .github/workflows/acceptance-tests-on-emulator.yaml
- .github/workflows/acceptance-tests-on-production.yaml
- .github/workflows/ci.yaml
- .github/workflows/release-please-label.yml
- .github/workflows/rubocop.yaml
- CONTRIBUTING.md
- README.md
Fix the branch name (`master` -> `main`) for several workflows. Also fix a few links referencing the old branch name. I set this PR as "chore" because github will forward links with the old branch name so we don't need to release a fixed gem. Rather, this will fix CI so we actually get proper continuous runs when PRs are merged.
> chore: Fix default branch in a bunch of workflow configs

- README.md
Per the discussion of #160, I added the current limitation of using interleaved tables.
> docs: add limitation of interleaved tables to README

- acceptance/cases/type/all_types_test.rb
- lib/active_record/connection_adapters/spanner_adapter.rb
- lib/active_record/type/spanner/array.rb
Rails always assumes input of type `ActiveRecord::Type` to be cast/converted to the appropriate database type, but `ActiveRecord::Type::Spanner::Array` does not serialize and does not cast/convert values correctly from/to the database type in all cases.
This can cause exceptions if the array elements that are passed in are not of the expected database type (e.g. trying to use a string value in a float64 array).
Fixes #163
> fix: ActiveRecord::Type::Spanner::Array does not use element type

- acceptance/cases/type/all_types_test.rb
- acceptance/cases/type/json_test.rb
- acceptance/schema/schema.rb
- acceptance/test_helper.rb
Enable JSON tests on the emulator now that the emulator also supports JSON columns.
> test: enable JSON tests on emulator

- .github/CODEOWNERS
- .github/sync-repo-settings.yaml
- .github/workflows/ci.yaml
Switch to github ruby teams that are managed by teamsync.
> chore: Update ruby github team names

- .github/workflows/acceptance-tests-on-emulator.yaml
- .github/workflows/nightly-acceptance-tests-on-emulator.yaml
- .github/workflows/nightly-unit-tests.yaml
- Gemfile
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
The composite_primary_key gem does not work with ActiveRecord 6.1.0, 6.1.1 and 6.1.2 due to an API change in 6.1.3. That has caused build errors for the nightly builds in the past couple of weeks. This change updates the tested and supported versions of ActiveRecord and Ruby, and also adds the newest versions of ActiveRecord.
I've run all the nightly tests as part of this PR as well. See:
* Nightly acceptance tests: https://github.com/googleapis/ruby-spanner-activerecord/actions/workflows/nightly-acceptance-tests-on-emulator.yaml
* Nightly unit tests: https://github.com/googleapis/ruby-spanner-activerecord/actions/workflows/nightly-unit-tests.yaml
> deps: update supported versions

- .kokoro/release.sh
- .toys/release.rb
`pip install` without a hash check is considered unsafe from a software supply chain perspective. Currently the release script does that to install python tools for the release process. The Ruby team has provided a safe install mechanism for the release-related python packages (`gcp-releasetool` and `gcp-docuploader`), and has implemented it centrally in the googleapis/ruby-common-tools repository. This PR updates the release script to call that install mechanism rather than invoking `pip install` directly.
> chore: Release scripts use a safer common tool to install python dependencies

- lib/activerecord_spanner_adapter/connection.rb
- lib/activerecord_spanner_adapter/transaction.rb
- lib/activerecord_spanner_adapter/version.rb
- test/test_helper.rb
I was getting an error that `Google::Spanner` was uninitialized. This update fixed it for me.
> fix: Corrected the namespace for the transaction selector class

- README.md
Document the support for ActiveRecord 7 in the README file.
> docs: add ActiveRecord 7 as a supported version to the README

- README.md
Cleanup the limitations section a little, so that:
1. Support for interleaved tables is correctly documented
2. The lack of default column values is removed, as it is now supported
> docs: update limitation on interleaved tables and default column values

- lib/active_record/connection_adapters/spanner/schema_definitions.rb
- lib/active_record/connection_adapters/spanner/schema_statements.rb
- test/migrations_with_mock_server/db/migrate/10_create_parent_and_child_with_uuid_pk.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
- test/migrations_with_mock_server/models/child_with_uuid_pk.rb
- test/migrations_with_mock_server/models/parent_with_uuid_pk.rb
Our schema uses string UUIDs as primary keys. We want to create composite keys with these UUIDs to utilize interleaving. This is not currently possible with `parent_key` assuming we want an INT64 column.
> feat: allows passing of type parameter when creating parent_key column

- lib/active_record/tasks/spanner_database_tasks.rb
- lib/activerecord_spanner_adapter/connection.rb
When recreating the database, ignore if it does not exist and continue to create the database as requested.
This mimics the rest of the AR adapters.
Fixes the `NoDatabaseError` that is raised if there is no database.
> fix: ignore no database when recreating

- acceptance/cases/migration/schema_dumper_test.rb
- examples/snippets/array-data-type/db/schema.rb
- examples/snippets/bulk-insert/db/schema.rb
- examples/snippets/commit-timestamp/db/schema.rb
- examples/snippets/create-records/db/schema.rb
- examples/snippets/date-data-type/db/schema.rb
- examples/snippets/generated-column/db/schema.rb
- examples/snippets/hints/db/schema.rb
- examples/snippets/interleaved-tables/db/schema.rb
- examples/snippets/migrations/db/schema.rb
- examples/snippets/mutations/db/schema.rb
- examples/snippets/optimistic-locking/db/schema.rb
- examples/snippets/partitioned-dml/db/schema.rb
- examples/snippets/quickstart/db/schema.rb
- examples/snippets/read-only-transactions/db/schema.rb
- examples/snippets/read-write-transactions/db/schema.rb
- examples/snippets/stale-reads/db/schema.rb
- examples/snippets/timestamp-data-type/db/schema.rb
- lib/active_record/connection_adapters/spanner/schema_dumper.rb
To speed up the loading of the schema.rb (in `rails db:schema:load`), load the entire schema in a batch.
> feat: schema_dumper should use DDL batch

- lib/active_record/connection_adapters/spanner/schema_creation.rb
- lib/active_record/connection_adapters/spanner/schema_statements.rb
- lib/active_record/connection_adapters/spanner_adapter.rb
- lib/activerecord_spanner_adapter/information_schema.rb
- test/activerecord_spanner_adapter/information_schema_test.rb
- test/migrations_with_mock_server/db/migrate/04_create_singer_and_album_and_track_tables.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
Support native rails check constraints in the Spanner adapter:
```
create_table :adults do |t|
t.integer :age, null: false
t.check_constraint 'age > 18', name: :chk_adults_age
end
```
Will generate the following constraint:
```
CONSTRAINT chk_adults_age CHECK(age > 18)
```
> feat: add check constraint support to migrations

- acceptance/cases/migration/schema_dumper_test.rb
- examples/snippets/commit-timestamp/db/schema.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/active_record/connection_adapters/spanner/schema_dumper.rb
- lib/active_record/connection_adapters/spanner/schema_statements.rb
- lib/active_record/connection_adapters/spanner/type_metadata.rb
- lib/active_record/type/spanner/spanner_active_record_converter.rb
- lib/active_record/type/spanner/time.rb
- lib/activerecord_spanner_adapter/base.rb
- lib/activerecord_spanner_adapter/information_schema.rb
- test/activerecord_spanner_adapter/information_schema_test.rb
- test/activerecord_spanner_interleaved_table/model_helper.rb
- test/activerecord_spanner_mock_server/model_helper.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
Some type classes are defined as delegates of other types, so the arity
of the `serialize` method will be -1 as it delegates the implementation.
This causes errors for timestamp columns that are timezone aware. This
detail was added due to the conditional nature of the Spanner commit
timestamp value depending on the query type, dml or in a mutation.
This was causing `ArgumentError`s under certain conditions when 
typecasting timezone aware attributes.
To make it more clear, define a explicit interface for the adapter to
use that takes the isolation level.
This also includes a feature to add `allow_commit_timestamp` to the Ruby
schema.rb
> fix: improve type commit_timestamp conversion detection

- acceptance/schema/schema.rb
- examples/snippets/array-data-type/db/schema.rb
- examples/snippets/bulk-insert/db/schema.rb
- examples/snippets/commit-timestamp/db/schema.rb
- examples/snippets/create-records/db/schema.rb
- examples/snippets/date-data-type/db/schema.rb
- examples/snippets/migrations/db/schema.rb
- examples/snippets/mutations/db/schema.rb
- examples/snippets/optimistic-locking/db/schema.rb
- examples/snippets/quickstart/db/schema.rb
- examples/snippets/read-write-transactions/db/schema.rb
- examples/snippets/timestamp-data-type/db/schema.rb
- lib/active_record/connection_adapters/spanner/schema_statements.rb
`create_table` had outdated logic that needed to be updated to Rails 6.1+ to allow for a `id: { limit: 8 }` option on the primary key (even though not used by the driver). The `limit: 8` is added due to the type definition of the INT64 columns.
> fix: schema with integer primary keys

- acceptance/cases/models/query_test.rb
- lib/arel/visitors/spanner.rb
`Relation#to_sql` disables prepared statements so the resulting SQL string has the binds interpolated into the statement. Keep the return value of the collector since the collector is context dependent.
> fix: ignore binds on unprepared statements

- acceptance/cases/sessions/session_not_found_test.rb
- acceptance/test_helper.rb
Hi! Env vars (`SPANNER_PROJECT` and `SPANNER_KEYFILE_JSON`) are set in Rakefile to be able to be configured in varias ways such as args and a some types of env vars so they should be also used in test code instead of env vars for single usecases.
It will make testing in local machines easy like:
```sh
SPANNER_EMULATOR_HOST=localhost:9010 bundle exec rake "acceptance[test-project,,testinstance]"
```
> chore: Change env var names used in tests

- acceptance/cases/sessions/session_not_found_test.rb
- acceptance/test_helper.rb
Reverts googleapis/ruby-spanner-activerecord#211
> Revert "chore: Change env var names used in tests"

- test/activerecord_spanner_interleaved_table/interleaved_tables_test.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
Adds a couple of tests for creating a model using `parent_model.child_models.create`.
> test: add tests for parent_model.child_models.create

- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/active_record/type/spanner/spanner_active_record_converter.rb
Fixes a test failure for Ruby 2.5. See https://github.com/googleapis/ruby-spanner-activerecord/actions/runs/3665608106
> fix: build error for ruby 2.5

- acceptance/cases/models/interleave_test.rb
- acceptance/models/album_partial_disabled.rb
- lib/activerecord_spanner_adapter/base.rb
Hi! I fixed an error on interleave.
[reproduction code](https://github.com/nownabe/bug-report-activerecord-spanner/tree/main/interleave)
With Rails 7 default config, creating a record into the interleaved child table causes an error like:
```
ActiveRecord::StatementInvalid: Google::Cloud::FailedPreconditionError: 9:Cannot specify a null value for column: albums.album_id in table: albums.
```
Rails 7 sets `partial_inserts` to `false` as default.
https://edgeguides.rubyonrails.org/configuring.html#config-active-record-partial-inserts
If a model's `partial_inserts` is set to `false`, each `value` has an instance of `ActiveModel::Attribute` even if the value is `nil`. Otherwise, nil values keep `nil` (`values` variable doesn't include nil values).
This difference comes from …
> fix: support Rails 7 default config in interleaved tables

- acceptance/cases/tasks/database_tasks_test.rb
- lib/active_record/tasks/spanner_database_tasks.rb
- lib/activerecord_spanner_adapter/connection.rb
Reorders the expected SQL script to match the order that is returned by production when a schema is dumped, and clears the cached information_schema after dropping and recreating a database. The latter is required to prevent the existing information_schema information to be reused for the new database with the same name as the dropped database (specifically the session would be reused).
> test: reorder expected sql script for prod and clear information_schema

- README.md
Adds a limitation to the README that this adapter can only be used with GoogleSQL Cloud Spanner databases, and not with PostgreSQL-dialect databases.
> docs: document only GoogleSQL-dialect limitation

- acceptance/cases/models/logging_test.rb
Modify the test to comply with the example from the test_helper for log testing.
Fixes #228
> test: log test should wait for notifications before checking for logged statements

- Gemfile
- acceptance/cases/migration/change_table_test.rb
This needs to be reverted as minitest 5.16 dropped support for Ruby 2.5. We can add this again when we drop support for Ruby 2.5.
Reverts googleapis/ruby-spanner-activerecord#217
> Revert "chore: upgrade minitest from 5.15 to 5.16"

- acceptance/cases/migration/change_schema_test.rb
- lib/active_record/connection_adapters/spanner/schema_creation.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
Seems to have been an oversight in #196
> fix: wrap default values in () as required

- README.md
Make the dialect compatibility and migrations best practices clearer, so first time users are less likely to miss these.
> docs: call out best practices and dialect compatibility

- acceptance/cases/migration/change_table_test.rb
https://github.com/rails/rails/pull/47293 fixed an issue that required us to call the index_exists? method in two different ways in our tests, depending on the Ruby version that was being used. This is no longer needed for versions 7.0.5 and higher.
Fixes #255
> test: use new call syntax for ActiveRecord 7.0.5 and higher

- acceptance/cases/models/default_value_test.rb
- lib/activerecord_spanner_adapter/information_schema.rb
- test/activerecord_spanner_adapter/information_schema_test.rb
Default values from Information Schema should be properly unquoted because ActiveRecord uses default values from schema as values of new, unsaved records.
Fix #248
> fix: unquote string default value

- lib/active_record/connection_adapters/spanner/quoting.rb
Using Rails 7.0.7, the following error occurs when performing database migration.
This pull-req is a fix for this.
```bash
$ bundle exec rails db:migrate
rails aborted!
NoMethodError: undefined method `quoted_table_names' for ActiveRecord::ConnectionAdapters::SpannerAdapter:Class
```
see also: https://github.com/rails/rails/pull/48773/files
> fix: support for changes in Rails 7.0.7

- README.md
Updates the README to point to the sample with PGAdapter for using ActiveRecord with Cloud Spanner PostgreSQL-dialect databases.
> docs: update README to reference PGAdapter for PG

- examples/snippets/tags/README.md
- examples/snippets/tags/Rakefile
- examples/snippets/tags/application.rb
- examples/snippets/tags/config/database.yml
- examples/snippets/tags/db/migrate/01_create_tables.rb
- examples/snippets/tags/db/schema.rb
- examples/snippets/tags/db/seeds.rb
- examples/snippets/tags/models/album.rb
- examples/snippets/tags/models/singer.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/activerecord_spanner_adapter/connection.rb
- lib/arel/visitors/spanner.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
- test/test_helper.rb
Adds support for adding request and transaction tags through the annotate method.
Fixes #125
> feat: translate annotate to tags

- README.md
Ruby 2.6 is no longer supported
> deps: Drop support for Ruby 2.6

- acceptance/cases/models/insert_all_test.rb
- lib/activerecord_spanner_adapter/base.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
Credits to @abachman for creating #275. This PR is created separately to work around issues with the CLA check in the original PR.
Fixes #274
> fix: more permissive arg passthrough for insert_all and upsert_all

- examples/snippets/query-logs/README.md
- examples/snippets/query-logs/Rakefile
- examples/snippets/query-logs/application.rb
- examples/snippets/query-logs/config/database.yml
- examples/snippets/query-logs/db/migrate/01_create_tables.rb
- examples/snippets/query-logs/db/schema.rb
- examples/snippets/query-logs/db/seeds.rb
- examples/snippets/query-logs/models/album.rb
- examples/snippets/query-logs/models/singer.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/active_record/connection_adapters/spanner_adapter.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
Rails 7.0 introduced support for Query Logs. These automatically append comments to all SQL statements that are executed, so it is easier to find queries that perform badly. Cloud Spanner does not include comments from the SQL string in the query statistics, meaning that in order for these comments to be useful, they need to be translated to request tags.
This change modifies the query execution path so the query transformer that is used by Query Logs is called by the Cloud Spanner provider. The comments that are added can then be translated to request tags. The latter requires that Query Logs is configured with two specific options:
1. `ActiveRecord::QueryLogs.prepend_comment = true`
2. The first tag must be `{ request_tag:  "true" }`
See the included sample application for a full …
> feat: support Query Logs

- Gemfile
- lib/spanner_client_ext.rb
Replace `sub!` with `sub`, as not all dependency version declarations contain the prefix.
> build: remove bang from sub function in gem file

- README.md
- examples/snippets/bit-reversed-sequence/README.md
- examples/snippets/bit-reversed-sequence/db/migrate/01_create_tables.rb
- examples/snippets/bit-reversed-sequence/db/schema.rb
Update the bit-reversed sequence sample to actually use a bit-reversed sequence, and more clearly call out the requirement that a sequence name must be specified, and that ActiveRecord 7.1 must be used.
> docs: update bit-reversed sequence sample

- Rakefile
Hello,
I tried to run a local emulator test(command below) and found that it failed. It seemed to be due to the fact that the environment variable names were different from those used in the test, so I fixed it.
```shell
bundle exec rake "acceptance[dummy-project,,dummy-instance,]"
```
> fix: local emulator test

- acceptance/cases/tasks/database_tasks_test.rb
The database tasks test did not drop the test database after running, which caused a slow build-up of test databases on the test instance.
> test: drop database after test

- .github/workflows/nightly-unit-tests.yaml
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/active_record/connection_adapters/spanner/quoting.rb
- lib/active_record/connection_adapters/spanner_adapter.rb
- lib/activerecord-spanner-adapter.rb
- lib/activerecord_spanner_adapter/base.rb
The changes in 7.2.0 have made some of the code dirty, so please give me feedback if you have any good ideas.
see:
- https://github.com/rails/rails/pull/50064
- https://github.com/rails/rails/commit/0016280f4fde55d96738887093dc333aae0d107b#diff-9c10b17f0ee079f3e5294d17264e7e06986f6192cff165f6628fe99886c38c24L76
- https://github.com/rails/rails/commit/eabcff22a86213521eecafbf2dbf3ad82714f941#diff-88e231c48eb5559ac3be58a024b019e86f7c74d388f5d49fac3f4e47bf851cc6R516
> feat: support Rails 7.2.0

- .github/workflows/acceptance-tests-on-emulator.yaml
- .github/workflows/ci.yaml
- .github/workflows/nightly-acceptance-tests-on-emulator.yaml
- acceptance/cases/migration/schema_dumper_test.rb
- acceptance/test_helper.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/active_record/connection_adapters/spanner/quoting.rb
- lib/active_record/connection_adapters/spanner/schema_statements.rb
- lib/activerecord_spanner_adapter/base.rb
- lib/activerecord_spanner_adapter/connection.rb
- test/activerecord_spanner_interleaved_table_version_7_1_and_higher/interleaved_tables_test.rb
- test/activerecord_spanner_mock_server/base_spanner_mock_server_test.rb
@olavloite 
I'm very sorry!!
I had committed the code I wrote for debugging as is...
Please check that I have fixed it.
> fix: Fixed incorrect argument handling.

- acceptance/cases/models/insert_all_test.rb
- acceptance/cases/sessions/session_not_found_test.rb
- lib/active_record/connection_adapters/spanner_adapter.rb
- lib/activerecord_spanner_adapter/base.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
Add support for `INSERT OR [IGNORE|UPDATE]` DML statements.
> feat: INSERT OR [IGNORE|UPDATE]

- .github/workflows/acceptance-tests-on-emulator.yaml
- .github/workflows/ci.yaml
- .github/workflows/nightly-acceptance-tests-on-emulator.yaml
- .github/workflows/nightly-unit-tests.yaml
- .github/workflows/samples.yaml
- acceptance/cases/migration/command_recorder_test.rb
- acceptance/cases/migration/references_index_test.rb
- lib/active_record/connection_adapters/spanner/schema_statements.rb
- test/activerecord_spanner_adapter/information_schema_test.rb
- test/migrations_with_mock_server/db/migrate/04_create_singer_and_album_and_track_tables.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
Drops support for Rails 6.1 as it is no longer supported.
See https://rubyonrails.org/2024/10/15/new-maintenance-policy-and-eol-annouments
> feat!: drop support for Rails 6.1

- test/activerecord_spanner_mock_server/pessimistic_locking_test.rb
Spanner now supports SELECT .. FOR UPDATE clauses. This change adds a test that verifies that the Spanner ActiveRecord provider generates the correct SELECT .. FOR UPDATE statements when a pessimistic lock is requested.
See also https://cloud.google.com/spanner/docs/release-notes#January_27_2025
> docs: add a test to verify that FOR UPDATE can be used

- .github/workflows/acceptance-tests-on-emulator.yaml
- .github/workflows/ci.yaml
- acceptance/cases/tasks/database_tasks_test.rb
- acceptance/test_helper.rb
- activerecord-spanner-adapter.gemspec
- examples/snippets/isolation-level/README.md
- examples/snippets/isolation-level/Rakefile
- examples/snippets/isolation-level/application.rb
- examples/snippets/isolation-level/config/database.yml
- examples/snippets/isolation-level/db/migrate/01_create_tables.rb
- examples/snippets/isolation-level/db/seeds.rb
- examples/snippets/isolation-level/models/album.rb
- examples/snippets/isolation-level/models/singer.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/active_record/connection_adapters/spanner_adapter.rb
- lib/activerecord_spanner_adapter/connection.rb
- lib/activerecord_spanner_adapter/transaction.rb
- test/activerecord_spanner_interleaved_table/interleaved_tables_test.rb
- test/activerecord_spanner_interleaved_table_version_7_1_and_higher/interleaved_tables_test.rb
- test/activerecord_spanner_mock_server/base_spanner_mock_server_test.rb
- test/activerecord_spanner_mock_server/inline_begin_transaction_test.rb
- test/migrations_with_mock_server/migrations_with_mock_server_test.rb
- test/test_helper.rb
Add support for :repeatable_read transaction isolation level. This can be used in the following ways:
- By passing in a value for the :isolation argument when starting a transaction.
- By setting the :isolation_level property of a connection.
- By setting the :isolation_level property in the database config.
> feat: transaction isolation level

- lib/arel/visitors/spanner.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
Not sure there's a perfect place for this to live in activerecord but an optimizer hint seemed pretty reasonable.
> Add optimizer hint syntax to set a priority in request options

- acceptance/cases/transactions/read_write_transactions_test.rb
- examples/snippets/partitioned-dml/application.rb
- lib/active_record/connection_adapters/spanner/database_statements.rb
- lib/active_record/connection_adapters/spanner/errors/transaction_mutation_limit_exceeded_error.rb
- lib/activerecord_spanner_adapter/connection.rb
- lib/activerecord_spanner_adapter/transaction.rb
- test/activerecord_spanner_mock_server/spanner_active_record_with_mock_server_test.rb
**Description:**
This change introduces an opt-in, automatic retry mechanism for DML statement that fails due to Spanner's transaction mutation limit.
When a DML statement fails with a TransactionMutationLimitExceededError, this logic will automatically retry the statement within a new Partitioned DML (PDML) transaction.
**Key Features:**
* The fallback is transparent and enabled by passing a fallback_to_pdml isolation option to a standard transaction block.
* If the fallback is disabled or unsafe, a specific TransactionMutationLimitExceededError is raised.
**Usage:**
```
Singer.transaction(isolation: fallback_to_pdml) do
Singer.where("last_name LIKE ?", "A%").update_all(status: "Archived")
end
```
> feat: Add automatic PDML fallback for mutation limit errors
